### ISSUE TITLE
fix to error handling

### ISSUE THREAD

**Issue by torroid** [vngx/vngx-jsch#1]
Catch clause in UserAuth.java at line 284 should be for Error, not Exception. Otherwise it can't catch:
Exception in thread "main" java.lang.VerifyError: (class: org/vngx/jsch/userauth/UserAuthPublicKey, method: authUser signature: (Lorg/vngx/jsch/Session;[B)Z) Illegal default target in switch

**Comment by vngx** [comment]
I'm currently investigating the issue.  Can you reproduce the issue?  And can you provide any more information about what were the conditions when the error occurred?

**Comment by scott2449** [comment]
It's generally not a good idea to catch errors. We'd like to refactor the code to deal w/ your issue more gracefully, so please send us as much information as possible. Thanks in advance!

**Comment by rickyclarkson** [comment]
This looks like a problem in the compiled Java bytecode, i.e., a Java bug.  I've just come across it myself too.

**Comment by knalli** [comment]
I'm just running in the same issue.. lucky, the 2nd result of google of the common phrase "Illegal switch" linked to this issue.

What's about the patch? Should we test again this before you can apply it?
