### ISSUE TITLE
Can't resolve com.springsource.com.jcraft.jzlib using Grape

### ISSUE THREAD

**Issue by matschaffer** [vngx/vngx-jsch#11]
This could be just an issue with Grape, but I can't seem to download your dependency on com.springsource.com.jcraft.jzlib. I get this error

```
java.lang.RuntimeException: Error grabbing Grapes -- [unresolved dependency: com.jcraft.jzlib#com.springsource.com.jcraft.jzlib;1.0.7: not found]
```

Is that really the intended artifact? I can't find anything that looks like it on http://search.maven.org/ either.

**Comment by scott2449** [comment]
You have to have the spring source maven repos configured:

https://github.com/vngx/vngx-jsch/blob/master/pom.xml#L118

The normal repos will not contain this version and I would assume that is what grape is trying to use. You can also modify the pom (if you don't care about virgo support) to use the normal jzlib package.
