### ISSUE TITLE
How do I use this instead of JSCH?

### ISSUE THREAD

**Issue by hendorog** [vngx/vngx-jsch#14]
Any docs or examples or clues to use this? 
It could be awesome as the JSCH vague error problem is legendary, but I've no idea how to use it...

**Comment by marcosox** [comment]
After trying this, the old Jsch, SshJ and a couple other libraries, I have a very late advice for anyone using this: don't bother. Use Apache MINA SSHD's `SshClient` instead. It's actively maintained, works with default JCE out of the box and is mostly documented.

**Comment by scott2449** [comment]
Agreed we stopped maintaining this because there was no appetite. We were apparently the only ones who understood how 💩 jsch was under the hood.
