### ISSUE TITLE
Make a new Maven Release

### ISSUE THREAD

**Issue by pmaedel** [vngx/vngx-jsch#6]
Currently, vngx-jsch at version 0.9 as available from maven central, still has the OS X specific bugs.

Please perform a new release, so the fixes of Issue 1 & 2, are available to new users without further effort.

**Comment by scott2449** [comment]
I will try and do this soon. I need a few spare minutes to remind myself of the bundle process. It should be quicker than the first time because the app is approved (first time took weeks). I'll update/close this when it's ready.
