### ISSUE TITLE
JSch.addIdentity() is not available

### ISSUE THREAD

**Issue by evgeny-goldin** [vngx/vngx-jsch#7]
Hi, I've created a [fork](https://github.com/evgeny-goldin/ant-vngx-jsch) of "ant-jsch" to use "org.vngx:vngx-jsch" rather than "com.jcraft:jsch". Most of the calls mapped easily to the new code but I couldn't find a way to make a `org.vngx.jsch.JSch.addIdentity(userKeyFile)` [call](https://github.com/evgeny-goldin/ant-vngx-jsch/blob/001ca69dee0a05c35f5f1dd414f05bade9e297c0/src/main/java/com/github/goldin/ant/vngx/jsch/SSHBase.java#L212).

Could you show me the way? Thanks!

**Comment by scott2449** [comment]
https://github.com/vngx/vngx-jsch/blob/master/src/main/java/org/vngx/jsch/userauth/IdentityManager.java#L80 i.e.  `org.vngx.jsch.userauth.IdentityManager.getManager.addIdentity()` You'll have to string the file yourself. If you'd really prefer file submit a request with the overridden method. Hope that helps.

**Comment by evgeny-goldin** [comment]
Thanks!

**Comment by arcones** [comment]
Hello,

I am trying to do the same as evgeny-goldin and I have problems to transform this chunk of code dependant on jsch library:

_Jsch = new JSch(); //I have replaced this by _Jsch = JSch.getInstance();
 _Jsch.addIdentity(_PathPriv); //this is the part where I have most of the problems
_Session = _Jsch.getSession(_User, _Host, _Port); //I have replaced this by _Session = _Jsch.createSession(_User, _Host, _Port);

Any idea? If I use the IdentityManager I end up having two objects, the JSch and the IdentityManager and I don't know how to relate them...

I have attached the original source dependant on JSCH library
[SCPAuthSender.zip](https://github.com/vngx/vngx-jsch/files/420261/SCPAuthSender.zip)
