### ISSUE TITLE
wrong jzlib dependency 

### ISSUE THREAD

**Issue by jkot** [vngx/vngx-jsch#8]
There's no com.springsource.com.jcraft.jzlib in the central maven repository. At least not now.

There is http://search.maven.org/remotecontent?filepath=com/jcraft/jzlib/1.1.1/jzlib-1.1.1.pom which is different.

**Comment by scott2449** [comment]
Nor should there be. If you examine the pom you will see we are depending on the OSGi complaint version of jzlib which is hosted by springsource. http://ebr.springsource.com/repository/app/bundle/version/detail?name=com.springsource.com.jcraft.jzlib&version=1.0.7&searchType=bundlesBySymbolicName&searchQuery=jzlib

**Comment by jkot** [comment]
right, I was too quick, thanks!

**Comment by scott2449** [comment]
=)
